on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - not_existent
  pull_request:
    branches:
      - not_existent

jobs:
  check_pull:
    # we use jobs in a matrix.
    # the OS to be used for the test is taken from the current matrix element
    runs-on: ${{ matrix.os }}
    strategy:
      # we want to avoid to stop all the tests the first time that one of them gets an error
      fail-fast: false
      matrix:
        include:
        #here we set up the various matrix elements
        #the entries in each matrix element are just variables, not keywords, with (hopefully) self-explaining names
        # 1st matrix element, default compiler at FIAS
        - os: ubuntu-18.04
          site: "fias"
          packages_to_add: "libboost-all-dev g++-5 doxygen-latex graphviz libgsl-dev"
          c_compiler_to_use: "gcc-5"
          cxx_compiler_to_use: "g++-5"
        # 2nd matrix element, recent LTS Ubuntu distribution with gcc
        - os: ubuntu-20.04
          site: "linux-default-gcc"
          packages_to_add: "libboost-all-dev doxygen-latex graphviz libgsl-dev"
          c_compiler_to_use: "gcc"
          cxx_compiler_to_use: "g++"
        # 3rd matrix element, recent LTS Ubuntu distribution with clang
        - os: ubuntu-20.04
          site: "linux-default-clang"
          packages_to_add: "libboost-all-dev libgsl-dev"
          c_compiler_to_use: "clang"
          cxx_compiler_to_use: "clang++"
        # 4th matrix element, osx 11 with clang
        - os: macos-11
          site: "mac"
          packages_to_add: "boost gsl"
          c_compiler_to_use: "clang"
          cxx_compiler_to_use: "clang++"
        # 5th matrix element, default compiler in Goethe cluster
        - os: ubuntu-18.04
          # this time we do not include boost, we compile it later by ourselves
          site: "goethe"
          packages_to_add: "g++-4.8 libgsl-dev"
          c_compiler_to_use: "gcc-4.8"
          cxx_compiler_to_use: "g++-4.8"
    steps:
    # this is an action provided by GitHub to checkout the repository
    - uses: actions/checkout@v2
    # we set the name of the step, collecting all the tests in just one step
    - name: code_check
    # we set some environment variables for the specific OS version
      env:
        CC: ${{ matrix.c_compiler_to_use }}
        CXX: ${{ matrix.cxx_compiler_to_use }}
        OS_NAME: ${{ matrix.os }}
        SITE: ${{ matrix.site }}
      # we run the step. We recall that in YAML the pipe symbol "|" means that the follwing lines, including newlines, are interpreted literally
      run: |
        # which version of cmake is used
        cmake --version
        # we set the smash root directory
        export SMASH_ROOT=$PWD
        # we get cpplint
        wget https://raw.githubusercontent.com/cpplint/cpplint/develop/cpplint.py && chmod +x cpplint.py && mkdir -p $HOME/bin && mv cpplint.py $HOME/bin
        export PATH=$HOME/bin:$PATH
        cpplint.py --version
    # We now setup python environment to then install cmake-format, but we do so on one site only
    # since we are going to test only there whether the codebase is correctly formatted or not
    - if: matrix.site == 'linux-default-gcc'
      # this is an other GitHub action to properly setup the python environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: code_format_check
      if: matrix.site == 'linux-default-gcc'
      run: |
        # we set the smash root directory
        export SMASH_ROOT=$PWD
        # we download and unpack clang to have clang-format available
        curl -# -o clang6_0_0.tar.xz https://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz &&
        mkdir clang6_0_0 && tar -xf clang6_0_0.tar.xz -C clang6_0_0 --strip-components=1 && rm clang6_0_0.tar.xz
        # we install cmake-format in a dedicated directory and adjust environment
        mkdir $SMASH_ROOT/python-tools && pip install --target $SMASH_ROOT/python-tools cmakelang==0.6.13
        export PYTHONPATH=$SMASH_ROOT/python-tools:$PYTHONPATH
        # we check the correct formatting of the code
        printf "cmake-format --version: "
        PATH=$SMASH_ROOT/python-tools/bin/:$PATH cmake-format --version
        echo "Python version: $(python --version)"
        echo "Pip    version: $(pip --version)"
        PATH=$SMASH_ROOT/clang6_0_0/bin/:$PATH clang-format --version